apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hyunn915@gmail.com
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
    - dns01:
        route53:
          region: ap-northeast-1
          hostedZoneID: Z0553794203F3FWUIKR5V
          role: arn:aws:iam::243795305209:role/RoleForCertManager
      selector:
        dnsZones:
          - "btcloud.site"
